#!/bin/bash

# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	package_dirs=/usr/share/python-support/python-pymongo.public
	if test -f $package_dirs; then
		update-python-modules -v --post-install $package_dirs
	else
		update-python-modules python-pymongo
	fi
fi