#!/bin/bash

# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	if test -f /usr/share/python-support/python-pbr.public; then
		update-python-modules -v --post-install /usr/share/python-support/python-pbr.public
	else
		update-python-modules pbr
	fi
fi